/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Contacto;
import java.util.Map;
import javax.swing.DefaultListModel;



/**
 *
 * @author Centeno-Net
 */
public class frmBuscarCliente extends javax.swing.JInternalFrame {

    private DefaultListModel<Long> modeloLista = new DefaultListModel<>();

    /**
     * Creates new form frmBuscarCliente
     */
    public frmBuscarCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbbusquedaCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txTelefonoBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txDni = new javax.swing.JTextField();
        txApellido = new javax.swing.JTextField();
        txNombre = new javax.swing.JTextField();
        txCiudad = new javax.swing.JTextField();
        txDomicilio = new javax.swing.JTextField();
        btSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();

        jLabel1.setText("Telefonos:");

        lbbusquedaCliente.setText("Busqueda de Clientes");

        jLabel2.setText("Teléfono:");

        txTelefonoBusqueda.addActionListener(this::txTelefonoBusquedaActionPerformed);

        jLabel3.setText("Dni:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Ciudad:");

        jLabel7.setText("Domicilio:");

        btSalir.setText("Salir");
        btSalir.addActionListener(this::btSalirActionPerformed);

        jScrollPane3.setViewportView(jListTelefonos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txTelefonoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txDni)
                            .addComponent(txNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txApellido)
                            .addComponent(txCiudad)
                            .addComponent(txDomicilio)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbbusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbbusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txTelefonoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalir))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txTelefonoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefonoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefonoBusquedaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void jListTelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTelefonosValueChanged
        if (!evt.getValueIsAdjusting()) {
            String telStr = jListTelefonos.getSelectedValue();
            try {
                Long telefono = Long.parseLong(telStr);
                Contacto contacto = Principal.directorio.buscarContacto(telefono);
                
                if (contacto != null) {
                    txDni.setText(String.valueOf(contacto.getDni()));
                    txApellido.setText(contacto.getApellido());
                    txNombre.setText(contacto.getNombre());
                    txCiudad.setText(contacto.getCiudad());
                    txDomicilio.setText(contacto.getDireccion());
                    
                    // Opcional: autocompletar también el campo de búsqueda rápida por texto
                    txTelefonoBusqueda.setText(telStr);
                }
            } catch (NumberFormatException e) {
              
            }
        }
        
    }//GEN-LAST:event_jListTelefonosValueChanged
    private void txTelefonoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {                                               
        modeloLista.clear();
        String filtro = txTelefonoBusqueda.getText().trim();

        for (Map.Entry<Long, Contacto> entry : Principal.directorio.directorio.entrySet()) {
            String telStr = String.valueOf(entry.getKey());
            if (telStr.contains(filtro)) {
                modeloLista.addElement(entry.getKey());
            }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListTelefonos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbbusquedaCliente;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txCiudad;
    private javax.swing.JTextField txDni;
    private javax.swing.JTextField txDomicilio;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefonoBusqueda;
    private void cargarListaTelefonos() {
        modeloLista.clear();
        for (Long tel : Principal.directorio.obtenerTelefonos()) {
            modeloLista.addElement(tel);
        }
    }

    private void txfdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfdniActionPerformed

    private void txfdomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfdomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfdomicilioActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txfciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfciudadActionPerformed

    private void jlisttelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlisttelefonosValueChanged
        
    }//GEN-LAST:event_jlisttelefonosValueChanged

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListTelefonos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbbusquedaCliente;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txCiudad;
    private javax.swing.JTextField txDni;
    private javax.swing.JTextField txDomicilio;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefonoBusqueda;
    // End of variables declaration//GEN-END:variables



