package Vistas;

import Entidades.Contacto;
import Entidades.DirectorioTelefonico;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmBorrarCliente extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultListModel modeloLista = new DefaultListModel();

    public frmBorrarCliente() {
        initComponents();
        cabeceras();
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salirBTN = new javax.swing.JButton();
        borrarBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("DNI:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        salirBTN.setText("Salir");
        salirBTN.addActionListener(this::salirBTNActionPerformed);

        borrarBTN.setText("BORRAR");
        borrarBTN.addActionListener(this::borrarBTNActionPerformed);

        jList1.addListSelectionListener(this::jList1ValueChanged);
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarBTN)
                        .addGap(195, 195, 195)
                        .addComponent(salirBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBTN)
                    .addComponent(salirBTN))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBTNActionPerformed
        dispose();
    }//GEN-LAST:event_salirBTNActionPerformed

    private void borrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTNActionPerformed

        //ELIMINA LA FILA SELECCIONADA
        try {
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Primero agregue contactos!");
            } else {
                modelo.removeRow(jTable1.getSelectedRow());
            }
            
        } catch (Exception IndexOutOfBoundsException) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila!");
        }

        //ELIMINA EL CONTACTO DEL DIRECTORIO
        String lista = String.valueOf(jList1.getSelectedValue());

        for (Map.Entry<Long, Contacto> aux : Principal.directorio.directorio.entrySet()) {
            Long tel = aux.getKey();
            Contacto contacto = aux.getValue();

            if (lista.equals(Integer.toString(contacto.getDni()))) {
                Principal.directorio.borrarContacto(tel);
            }
        }
    }//GEN-LAST:event_borrarBTNActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

        modelo.setRowCount(0);

        String seleccion = String.valueOf(jList1.getSelectedValue());

        for (Map.Entry<Long, Contacto> aux : Principal.directorio.directorio.entrySet()) {

            Long telefono = aux.getKey();
            Contacto contacto = aux.getValue();

            if (seleccion.equals(Integer.toString(contacto.getDni()))) {

                String DNI = Integer.toString(contacto.getDni());
                String apellido = contacto.getApellido();
                String nombre = contacto.getNombre();
                String dir = contacto.getDireccion();
                String city = contacto.getCiudad();
                String tel = Long.toString(telefono);

                modelo.addRow(new String[]{DNI, apellido, nombre, dir, city, tel});

            }

        }
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton salirBTN;
    // End of variables declaration//GEN-END:variables

    private void cabeceras() {
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Telefono");

        jTable1.setModel(modelo);
        jList1.setModel(modeloLista);
    }

    private void cargarLista() {

        for (Contacto contacto : Principal.directorio.directorio.values()) {
            modeloLista.addElement(contacto.getDni());
        }

    }
}
